name: trailblazers_wiki
services:
  app:
    build: .
    volumes:
      - /home/trailblazer_server/TrailblazersWebsite/content/Obsidian/Trailblazers/Trailblazers:/usr/src/app/content

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.trailblazers.rule=Host(`trailblazers.bardicinspiration.cc`)'
      - 'traefik.http.services.trailblazers.loadbalancer.server.port=8100'
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true