name: tb_wiki
services:
  app-blue:
    build: .
    volumes:
      - /home/trailblazer_server/filewatcher/wiki_content/content-blue/Obsidian/Trailblazers/Trailblazers:/usr/src/app/content
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.trailblazers-blue.rule=Host(`trailblazers.bardicinspiration.cc`)'
      - "traefik.http.routers.app-blue.priority=10"
      - 'traefik.http.services.trailblazers-blue.loadbalancer.server.port=8100'
      - "traefik.http.middlewares.no-cache.headers.customResponseHeaders.Cache-Control=no-cache, no-store, must-revalidate" # Prevent caching
      - "traefik.http.routers.trailblazers-blue.middlewares=no-cache"
    networks:
      - traefik_web

  app-green:
    build: .
    volumes:
      - /home/trailblazer_server/filewatcher/wiki_content/content-green/Obsidian/Trailblazers/Trailblazers:/usr/src/app/content 
    labels:
      - 'traefik.enable=true' 
      - 'traefik.http.routers.trailblazers-green.rule=Host(`trailblazers.bardicinspiration.cc`)'
      - "traefik.http.routers.app-green.priority=20"
      - 'traefik.http.services.trailblazers-green.loadbalancer.server.port=8100'
      - "traefik.http.middlewares.no-cache.headers.customResponseHeaders.Cache-Control=no-cache, no-store, must-revalidate"
      - "traefik.http.routers.trailblazers-green.middlewares=no-cache" 
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true